"""Score one summarisation system on a test split and record it in benchmarks/raw/results.csv.

    python ml/evaluate.py --system extractive
    python ml/evaluate.py --system zero-shot                              # google/flan-t5-base as-is
    python ml/evaluate.py --system finetuned --model <hub-id-or-folder>   # our checkpoint
    python ml/evaluate.py --table                                         # rewrite the markdown table only

Each run replaces the csv row with the same (system, model, dataset, split, n), writes the
predictions to benchmarks/raw/predictions/, and regenerates benchmarks/summarization_results.md
from the csv, so the table never holds a number that is not in the csv.
"""

import argparse
import csv
import json
import platform
import sys
import time
from datetime import date
from pathlib import Path

ML_DIR = Path(__file__).resolve().parent
REPO_DIR = ML_DIR.parent
sys.path.insert(0, str(ML_DIR))

from data.format import build_input  # noqa: E402
from data.prepare import load_splits  # noqa: E402
from metrics import bertscore, rouge  # noqa: E402

RESULTS_CSV = REPO_DIR / "benchmarks" / "raw" / "results.csv"
PREDICTIONS_DIR = REPO_DIR / "benchmarks" / "raw" / "predictions"
TABLE_MD = REPO_DIR / "benchmarks" / "summarization_results.md"
FIELDS = [
    "system",
    "model",
    "dataset",
    "split",
    "n",
    "rouge1",
    "rouge2",
    "rougeL",
    "rougeLsum",
    "bertscore_f1",
    "bertscore_model",
    "num_beams",
    "max_input",
    "seconds",
    "device",
    "date",
]
SYSTEM_ORDER = {"extractive": 0, "zero-shot": 1, "finetuned": 2}


def generate(model_name: str, inputs: list[str], args: argparse.Namespace) -> tuple[list[str], str]:
    import torch
    from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

    device = args.device if args.device != "auto" else ("cuda" if torch.cuda.is_available() else "cpu")
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForSeq2SeqLM.from_pretrained(model_name).to(device).eval()

    # longest inputs first so each batch pads as little as possible; results are put back in order
    order = sorted(range(len(inputs)), key=lambda i: -len(inputs[i]))
    outputs: list[str] = [""] * len(inputs)
    for start in range(0, len(order), args.batch_size):
        batch_ids = order[start : start + args.batch_size]
        enc = tokenizer(
            [inputs[i] for i in batch_ids],
            max_length=args.max_input,
            truncation=True,
            padding=True,
            return_tensors="pt",
        ).to(device)
        with torch.inference_mode():
            generated = model.generate(**enc, max_new_tokens=args.max_target, num_beams=args.num_beams)
        for i, text in zip(
            batch_ids, tokenizer.batch_decode(generated, skip_special_tokens=True), strict=True
        ):
            outputs[i] = text.strip()
        done = min(start + args.batch_size, len(order))
        print(f"  generated {done}/{len(order)}", end="\r", flush=True)
    print()
    return outputs, device


def read_rows() -> list[dict]:
    if not RESULTS_CSV.exists():
        return []
    with RESULTS_CSV.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def write_rows(rows: list[dict]) -> None:
    RESULTS_CSV.parent.mkdir(parents=True, exist_ok=True)
    rows.sort(key=lambda r: (r["dataset"], r["split"], SYSTEM_ORDER.get(r["system"], 9), r["model"]))
    with RESULTS_CSV.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=FIELDS)
        writer.writeheader()
        writer.writerows(rows)


def markdown_table(rows: list[dict]) -> str:
    lines = [
        "| System | Model | Dataset / split | n | ROUGE-1 | ROUGE-2 | ROUGE-L | ROUGE-Lsum | BERTScore F1 |",
        "|--------|-------|-----------------|--:|--------:|--------:|--------:|-----------:|-------------:|",
    ]
    for r in rows:
        bs = r["bertscore_f1"] or "—"
        lines.append(
            f"| {r['system']} | {r['model']} | {r['dataset']} / {r['split']} | {r['n']} | {r['rouge1']} | "
            f"{r['rouge2']} | {r['rougeL']} | {r['rougeLsum']} | {bs} |"
        )
    return "\n".join(lines)


def write_markdown(rows: list[dict]) -> None:
    bs_models = sorted({r["bertscore_model"] for r in rows if r["bertscore_model"]})
    text = (
        "# Summarization results\n\n"
        "Generated by `python ml/evaluate.py` from `benchmarks/raw/results.csv` — do not edit by hand.\n\n"
        + markdown_table(rows)
        + "\n\nScores are F-measures in [0, 1]; ROUGE with Porter stemming, ROUGE-Lsum on one sentence per line. "
        + (f"BERTScore F1 uses `{', '.join(bs_models)}` without baseline rescaling. " if bs_models else "")
        + "Generation settings (beams, input length), wall time and device for every row are in the csv; "
        "per-example predictions are in `benchmarks/raw/predictions/`.\n"
    )
    TABLE_MD.write_text(text, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--system", choices=["extractive", "zero-shot", "finetuned"])
    parser.add_argument(
        "--model", default="google/flan-t5-base", help="hub id or local folder (zero-shot/finetuned)"
    )
    parser.add_argument("--label", default=None, help="model name recorded in the csv (default: --model)")
    parser.add_argument("--dataset", default="samsum")
    parser.add_argument("--split", default="test")
    parser.add_argument(
        "--max_samples", type=int, default=None, help="first n examples only, for quick checks"
    )
    parser.add_argument("--k", type=int, default=2, help="turns kept by the extractive baseline")
    parser.add_argument("--max_input", type=int, default=1024)
    parser.add_argument("--max_target", type=int, default=128)
    parser.add_argument("--num_beams", type=int, default=4)
    parser.add_argument("--batch_size", type=int, default=16)
    parser.add_argument("--device", default="auto")
    parser.add_argument("--bertscore_model", default="roberta-large")
    parser.add_argument("--no_bertscore", action="store_true")
    parser.add_argument("--no_save", action="store_true", help="print scores without touching benchmarks/")
    parser.add_argument(
        "--table", action="store_true", help="only regenerate the markdown table from the csv"
    )
    args = parser.parse_args()

    if args.table:
        rows = read_rows()
        write_markdown(rows)
        print(markdown_table(rows))
        return
    if not args.system:
        parser.error("--system is required unless --table is given")

    data = load_splits(args.dataset)[args.split]
    if args.max_samples:
        data = data.select(range(min(args.max_samples, len(data))))
    dialogues, references, ids = data["dialogue"], data["summary"], data["id"]
    print(f"{args.system} on {args.dataset}/{args.split}: {len(dialogues)} examples")

    started = time.perf_counter()
    if args.system == "extractive":
        from extractive_baseline import textrank

        predictions, device, model_label = (
            [textrank(d, args.k) for d in dialogues],
            "cpu",
            f"textrank-k{args.k}",
        )
    else:
        predictions, device = generate(args.model, [build_input(d) for d in dialogues], args)
        model_label = args.label or args.model
    seconds = time.perf_counter() - started

    scores = rouge(predictions, references)
    bs = None if args.no_bertscore else bertscore(predictions, references, args.bertscore_model)
    print(json.dumps({**scores, "bertscore_f1": bs, "seconds": round(seconds, 1)}, indent=2))
    if args.no_save:
        return

    row = {
        "system": args.system,
        "model": model_label,
        "dataset": args.dataset,
        "split": args.split,
        "n": len(dialogues),
        **scores,
        "bertscore_f1": "" if bs is None else bs,
        "bertscore_model": "" if bs is None else args.bertscore_model,
        "num_beams": "" if args.system == "extractive" else args.num_beams,
        "max_input": "" if args.system == "extractive" else args.max_input,
        "seconds": round(seconds, 1),
        "device": device if device != "cpu" else f"cpu ({platform.processor() or platform.machine()})",
        "date": date.today().isoformat(),
    }
    key = ("system", "model", "dataset", "split", "n")
    rows = [r for r in read_rows() if tuple(str(r[f]) for f in key) != tuple(str(row[f]) for f in key)]
    write_rows(rows + [{f: str(v) for f, v in row.items()}])

    PREDICTIONS_DIR.mkdir(parents=True, exist_ok=True)
    safe_model = model_label.replace("/", "__")
    out = PREDICTIONS_DIR / f"{args.dataset}_{args.split}_{args.system}_{safe_model}.jsonl"
    with out.open("w", encoding="utf-8") as f:
        for i, pred, ref in zip(ids, predictions, references, strict=True):
            f.write(json.dumps({"id": i, "prediction": pred, "reference": ref}, ensure_ascii=False) + "\n")

    rows = read_rows()
    write_markdown(rows)
    print(markdown_table(rows))


if __name__ == "__main__":
    main()
